#!/usr/bin/env bash
#
# bundle_workshop.sh - Package the EAOHP 2026 APIM workshop materials
# into a single distributable zip.
#
# Bundles:
#   1. scripts/                          (8 .R scripts)
#   2. exercises/                        (Rmd, answers template, simulate script)
#   3. data/                             (dyad_data.RData, exercise_data.RData)
#   4. Dyadic Data Analysis in R.pptx    (32-slide workshop deck)
#   5. references.pdf                    (methods references handout)
#
# Output: EAOHP_2026_APIM_workshop.zip (placed next to this script),
# containing a single top-level folder EAOHP_2026_APIM_workshop/ with
# the five items plus a generated README.md inside.
#
# Run:  ./bundle_workshop.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- sources (edit here if you rename anything) ---
SCRIPTS_DIR="${SCRIPT_DIR}/scripts"
EXERCISES_DIR="${SCRIPT_DIR}/exercises"
DATA_DIR="${SCRIPT_DIR}/data"
PPTX_PDF="${SCRIPT_DIR}/Dyadic Data Analysis in R.pdf"
REFS_PDF="${SCRIPT_DIR}/references.pdf"

# --- output config ---
TOP_FOLDER="EAOHP_2026_APIM_workshop"
BUNDLE="${SCRIPT_DIR}/${TOP_FOLDER}.zip"

# --- sanity checks ---
missing=0
for p in "$SCRIPTS_DIR" "$EXERCISES_DIR" "$DATA_DIR" "$PPTX_PDF" "$REFS_PDF"; do
  [[ -e "$p" ]] || {
    echo "ERROR: missing source: $p" >&2
    missing=1
  }
done
[[ $missing -eq 0 ]] || {
  echo "Aborting." >&2
  exit 1
}

# --- rebuild bundle from scratch ---
[[ -f "$BUNDLE" ]] && {
  echo "Removing existing bundle: $BUNDLE"
  rm -f "$BUNDLE"
}

STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT

mkdir -p "$STAGE/$TOP_FOLDER"
cp -R "$SCRIPTS_DIR" "$STAGE/$TOP_FOLDER/"
cp -R "$EXERCISES_DIR" "$STAGE/$TOP_FOLDER/"
cp -R "$DATA_DIR" "$STAGE/$TOP_FOLDER/"
cp "$PPTX_PDF" "$STAGE/$TOP_FOLDER/"
cp "$REFS_PDF" "$STAGE/$TOP_FOLDER/"

# Generate README.md from heredoc, with today's date substituted in.
BUILD_DATE="$(date +%Y-%m-%d)"
cat >"$STAGE/$TOP_FOLDER/README.md" <<EOF
# EAOHP 2026 APIM Workshop - Bundle

This bundle contains the materials for the EAOHP 2026 workshop on
dyadic data analysis with the Actor-Partner Interdependence Model
(APIM) in R.

## Contents

| Path | Description |
| --- | --- |
| \`scripts/\`   | R scripts for all 8 APIM estimation approaches (MLM and SEM; indistinguishable and distinguishable dyads; moderators; two-intercept; moderated APIM), plus the simulation script. |
| \`exercises/\` | Student exercises and answer template, and the simulation script that regenerates the exercise dataset. |
| \`data/\`      | Generated R datasets (\`dyad_data.RData\` from \`scripts/01_simulate_data.R\`, \`exercise_data.RData\` from \`exercises/simulate_exercise_data.R\`). The APIM scripts in \`scripts/02\`-08 load \`data/dyad_data.RData\`; the exercises load \`data/exercise_data.RData\`. |
| \`Dyadic Data Analysis in R.pdf\` | 32-slide workshop presentation. |
| \`references.pdf\` | Methods-references handout: foundational APIM papers, handbook chapters, SEM specification for indistinguishable dyads, k-pattern tutorial, R / lavaan implementation, intensive-longitudinal extension, and the applied example. |

## How to use

1. Open the presentation: \`Dyadic Data Analysis in R.pptx\`.
2. Run the R scripts in numeric order from \`scripts/\`. The simulation
   script (\`01_simulate_data.R\`) must be run first; it writes
   \`data/dyad_data.RData\`. The remaining scripts (02-08) load that
   file via \`load("../data/dyad_data.RData")\`.
3. Work through \`exercises/\` to extend each technique. Run
   \`exercises/simulate_exercise_data.R\` first to (re)create
   \`data/exercise_data.RData\`.
4. See \`references.pdf\` for the full reading list with one-line
   "when to read it" notes.

Generated by \`bundle_workshop.sh\` on ${BUILD_DATE}.
EOF

(cd "$STAGE" && zip -r -X -q "$BUNDLE" "$TOP_FOLDER")

echo
echo "Bundle: $BUNDLE"
echo "Size:   $(du -h "$BUNDLE" | cut -f1)"
echo
echo "Contents:"
unzip -l "$BUNDLE"
